FROM --platform=linux/amd64 alpine

WORKDIR /home

RUN apk add --no-cache openjdk8-jre wget
RUN wget https://github.com/lunes-platform/lunesnode/releases/download/0.1.0/lunesnode-0.1.0.jar
RUN wget https://github.com/lunes-platform/lunesnode/releases/download/0.1.0/lunesnode.conf

CMD []