name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run assembly
      run: sbt assembly
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: lunesnode 0.1.0
        path: target/lunesnode-0.1.0.jar